drop sequence FS_NODE_ID_SEQUENCE;
drop sequence FS_LINK_ID_SEQUENCE;
drop sequence FS_PRUNE_ID_SEQUENCE;
drop sequence FS_TREE_ID_SEQUENCE;

drop index fs_parent_depth_child_idx;
drop index fs_child_parent_depth_idx;

drop table FS_NODE;
drop table FS_CLOSURE;
drop table FS_PRUNE;
drop table FS_TREE;
drop table FS_TEST_NODE;

create table FS_NODE ( 
	NODE_ID NUMBER(15,0) NOT NULL, 
	PARENT_NODE_ID NUMBER(15,0) NOT NULL, 
   NODE_TYPE VARCHAR2(100) NOT NULL, 
	NAME VARCHAR2(250) NOT NULL, 
	CREATION_DATE date NOT NULL, 
	UPDATED_DATE date NOT NULL, 
	PRIMARY KEY (NODE_ID) 
);

create table FS_CLOSURE ( 
	LINK_ID NUMBER(15,0) NOT NULL, 
	PARENT_NODE_ID NUMBER(15,0) NOT NULL, 
	CHILD_NODE_ID NUMBER(15,0) NOT NULL, 
	DEPTH NUMBER(5,0) NOT NULL, 
	PRIMARY KEY (LINK_ID) 
);

create table FS_PRUNE ( 
	PRUNE_ID NUMBER(15,0) NOT NULL, 
	NODE_ID NUMBER(15,0) NOT NULL, 
	PRIMARY KEY (PRUNE_ID,NODE_ID) 
);	

create table FS_TREE ( 
	TREE_ID NUMBER(15,0) NOT NULL, 
	ROOT_NODE_ID NUMBER(15,0) NOT NULL, 
	NAME VARCHAR2(250) NOT NULL, 
	DESCRIPTION VARCHAR2(2000), 
	CREATION_DATE date NOT NULL, 
	UPDATED_DATE date NOT NULL, 
	PRIMARY KEY (TREE_ID) 
);

create table FS_TEST_NODE ( 
	NODE_ID NUMBER(15,0) NOT NULL, 
	TEST_VALUE VARCHAR2(250), 
	PRIMARY KEY (NODE_ID) 
);

create unique index fs_parent_depth_child_idx on fs_closure(parent_node_id,depth,child_node_id);
create unique index fs_child_parent_depth_idx on fs_closure(child_node_id,parent_node_id,depth);	

CREATE SEQUENCE FS_NODE_ID_SEQUENCE  
MINVALUE 1 
MAXVALUE 999999999999999999999999999  
INCREMENT BY 1 
START WITH 1 
CACHE 10  
ORDER  
NOCYCLE;

CREATE SEQUENCE FS_LINK_ID_SEQUENCE  
MINVALUE 1 
MAXVALUE 999999999999999999999999999  
INCREMENT BY 1 
START WITH 1 
CACHE 10  
ORDER  
NOCYCLE;

CREATE SEQUENCE FS_PRUNE_ID_SEQUENCE  
MINVALUE 1 
MAXVALUE 999999999999999999999999999  
INCREMENT BY 1 
START WITH 1 
CACHE 10  
ORDER  
NOCYCLE;

CREATE SEQUENCE FS_TREE_ID_SEQUENCE  
MINVALUE 1 
MAXVALUE 999999999999999999999999999  
INCREMENT BY 1 
START WITH 1 
CACHE 10  
ORDER  
NOCYCLE;